# .streamlit/secrets.toml

[connections.snowflake]
account = "xdb56712.us-east-1"
user = "shreyasj"
password = "Kipi8392"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "CONSUMPTION"
schema = "DELAY_DATA"
client_session_keep_alive = true